/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as R403RouteImport } from './routes/403'
import { Route as FrontendRouteRouteImport } from './routes/frontend/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrontendIndexRouteImport } from './routes/frontend/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as FrontendLoginRouteImport } from './routes/frontend/login'
import { Route as FrontendShellRouteImport } from './routes/frontend/_shell'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminShellRouteImport } from './routes/admin/_shell'
import { Route as FrontendShellTeamRouteImport } from './routes/frontend/_shell/team'
import { Route as FrontendShellHomeRouteImport } from './routes/frontend/_shell/home'
import { Route as FrontendShellAboutRouteImport } from './routes/frontend/_shell/about'
import { Route as AdminShellWidgetsRouteImport } from './routes/admin/_shell/widgets'
import { Route as AdminShellTenantsRouteImport } from './routes/admin/_shell/tenants'
import { Route as AdminShellProfileRouteImport } from './routes/admin/_shell/profile'
import { Route as AdminShellHomeRouteImport } from './routes/admin/_shell/home'
import { Route as AdminShellAuthLogRouteImport } from './routes/admin/_shell/auth-log'
import { Route as AdminShell404RouteImport } from './routes/admin/_shell/404'
import { Route as AdminShell403RouteImport } from './routes/admin/_shell/403'
import { Route as AdminShellUsersRouteRouteImport } from './routes/admin/_shell/users/route'
import { Route as AdminShellNestedRouteRouteImport } from './routes/admin/_shell/nested/route'
import { Route as AdminShellUsersIndexRouteImport } from './routes/admin/_shell/users/index'
import { Route as AdminShellNestedIndexRouteImport } from './routes/admin/_shell/nested/index'
import { Route as AdminShellUsersNewRouteImport } from './routes/admin/_shell/users/new'
import { Route as AdminShellUsersUserIdRouteImport } from './routes/admin/_shell/users/$userId'
import { Route as AdminShellNestedOverviewRouteImport } from './routes/admin/_shell/nested/overview'
import { Route as AdminShellNestedReportsRouteRouteImport } from './routes/admin/_shell/nested/reports/route'
import { Route as AdminShellNestedReportsIndexRouteImport } from './routes/admin/_shell/nested/reports/index'
import { Route as AdminShellUsersUserIdEditRouteImport } from './routes/admin/_shell/users/$userId_.edit'
import { Route as AdminShellNestedReportsDailyRouteImport } from './routes/admin/_shell/nested/reports/daily'
import { Route as AdminShellNestedReportsRegionsRouteRouteImport } from './routes/admin/_shell/nested/reports/regions/route'
import { Route as AdminShellNestedReportsRegionsIndexRouteImport } from './routes/admin/_shell/nested/reports/regions/index'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontendRouteRoute = FrontendRouteRouteImport.update({
  id: '/frontend',
  path: '/frontend',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontendIndexRoute = FrontendIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrontendRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const FrontendLoginRoute = FrontendLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => FrontendRouteRoute,
} as any)
const FrontendShellRoute = FrontendShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => FrontendRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AdminRouteRoute,
} as any)
const FrontendShellTeamRoute = FrontendShellTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => FrontendShellRoute,
} as any)
const FrontendShellHomeRoute = FrontendShellHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => FrontendShellRoute,
} as any)
const FrontendShellAboutRoute = FrontendShellAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => FrontendShellRoute,
} as any)
const AdminShellWidgetsRoute = AdminShellWidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellTenantsRoute = AdminShellTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellProfileRoute = AdminShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellHomeRoute = AdminShellHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellAuthLogRoute = AdminShellAuthLogRouteImport.update({
  id: '/auth-log',
  path: '/auth-log',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShell404Route = AdminShell404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShell403Route = AdminShell403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellUsersRouteRoute = AdminShellUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellNestedRouteRoute = AdminShellNestedRouteRouteImport.update({
  id: '/nested',
  path: '/nested',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellUsersIndexRoute = AdminShellUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShellUsersRouteRoute,
} as any)
const AdminShellNestedIndexRoute = AdminShellNestedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShellNestedRouteRoute,
} as any)
const AdminShellUsersNewRoute = AdminShellUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminShellUsersRouteRoute,
} as any)
const AdminShellUsersUserIdRoute = AdminShellUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminShellUsersRouteRoute,
} as any)
const AdminShellNestedOverviewRoute =
  AdminShellNestedOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AdminShellNestedRouteRoute,
  } as any)
const AdminShellNestedReportsRouteRoute =
  AdminShellNestedReportsRouteRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AdminShellNestedRouteRoute,
  } as any)
const AdminShellNestedReportsIndexRoute =
  AdminShellNestedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminShellNestedReportsRouteRoute,
  } as any)
const AdminShellUsersUserIdEditRoute =
  AdminShellUsersUserIdEditRouteImport.update({
    id: '/$userId_/edit',
    path: '/$userId/edit',
    getParentRoute: () => AdminShellUsersRouteRoute,
  } as any)
const AdminShellNestedReportsDailyRoute =
  AdminShellNestedReportsDailyRouteImport.update({
    id: '/daily',
    path: '/daily',
    getParentRoute: () => AdminShellNestedReportsRouteRoute,
  } as any)
const AdminShellNestedReportsRegionsRouteRoute =
  AdminShellNestedReportsRegionsRouteRouteImport.update({
    id: '/regions',
    path: '/regions',
    getParentRoute: () => AdminShellNestedReportsRouteRoute,
  } as any)
const AdminShellNestedReportsRegionsIndexRoute =
  AdminShellNestedReportsRegionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminShellNestedReportsRegionsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/frontend': typeof FrontendRouteRouteWithChildren
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/admin/login': typeof AdminLoginRoute
  '/frontend/login': typeof FrontendLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/frontend/': typeof FrontendIndexRoute
  '/admin/nested': typeof AdminShellNestedRouteRouteWithChildren
  '/admin/users': typeof AdminShellUsersRouteRouteWithChildren
  '/admin/403': typeof AdminShell403Route
  '/admin/404': typeof AdminShell404Route
  '/admin/auth-log': typeof AdminShellAuthLogRoute
  '/admin/home': typeof AdminShellHomeRoute
  '/admin/profile': typeof AdminShellProfileRoute
  '/admin/tenants': typeof AdminShellTenantsRoute
  '/admin/widgets': typeof AdminShellWidgetsRoute
  '/frontend/about': typeof FrontendShellAboutRoute
  '/frontend/home': typeof FrontendShellHomeRoute
  '/frontend/team': typeof FrontendShellTeamRoute
  '/admin/nested/reports': typeof AdminShellNestedReportsRouteRouteWithChildren
  '/admin/nested/overview': typeof AdminShellNestedOverviewRoute
  '/admin/users/$userId': typeof AdminShellUsersUserIdRoute
  '/admin/users/new': typeof AdminShellUsersNewRoute
  '/admin/nested/': typeof AdminShellNestedIndexRoute
  '/admin/users/': typeof AdminShellUsersIndexRoute
  '/admin/nested/reports/regions': typeof AdminShellNestedReportsRegionsRouteRouteWithChildren
  '/admin/nested/reports/daily': typeof AdminShellNestedReportsDailyRoute
  '/admin/users/$userId/edit': typeof AdminShellUsersUserIdEditRoute
  '/admin/nested/reports/': typeof AdminShellNestedReportsIndexRoute
  '/admin/nested/reports/regions/': typeof AdminShellNestedReportsRegionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/frontend': typeof FrontendIndexRoute
  '/frontend/login': typeof FrontendLoginRoute
  '/admin/403': typeof AdminShell403Route
  '/admin/404': typeof AdminShell404Route
  '/admin/auth-log': typeof AdminShellAuthLogRoute
  '/admin/home': typeof AdminShellHomeRoute
  '/admin/profile': typeof AdminShellProfileRoute
  '/admin/tenants': typeof AdminShellTenantsRoute
  '/admin/widgets': typeof AdminShellWidgetsRoute
  '/frontend/about': typeof FrontendShellAboutRoute
  '/frontend/home': typeof FrontendShellHomeRoute
  '/frontend/team': typeof FrontendShellTeamRoute
  '/admin/nested/overview': typeof AdminShellNestedOverviewRoute
  '/admin/users/$userId': typeof AdminShellUsersUserIdRoute
  '/admin/users/new': typeof AdminShellUsersNewRoute
  '/admin/nested': typeof AdminShellNestedIndexRoute
  '/admin/users': typeof AdminShellUsersIndexRoute
  '/admin/nested/reports/daily': typeof AdminShellNestedReportsDailyRoute
  '/admin/users/$userId/edit': typeof AdminShellUsersUserIdEditRoute
  '/admin/nested/reports': typeof AdminShellNestedReportsIndexRoute
  '/admin/nested/reports/regions': typeof AdminShellNestedReportsRegionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/frontend': typeof FrontendRouteRouteWithChildren
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/admin/_shell': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/frontend/_shell': typeof FrontendShellRouteWithChildren
  '/frontend/login': typeof FrontendLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/frontend/': typeof FrontendIndexRoute
  '/admin/_shell/nested': typeof AdminShellNestedRouteRouteWithChildren
  '/admin/_shell/users': typeof AdminShellUsersRouteRouteWithChildren
  '/admin/_shell/403': typeof AdminShell403Route
  '/admin/_shell/404': typeof AdminShell404Route
  '/admin/_shell/auth-log': typeof AdminShellAuthLogRoute
  '/admin/_shell/home': typeof AdminShellHomeRoute
  '/admin/_shell/profile': typeof AdminShellProfileRoute
  '/admin/_shell/tenants': typeof AdminShellTenantsRoute
  '/admin/_shell/widgets': typeof AdminShellWidgetsRoute
  '/frontend/_shell/about': typeof FrontendShellAboutRoute
  '/frontend/_shell/home': typeof FrontendShellHomeRoute
  '/frontend/_shell/team': typeof FrontendShellTeamRoute
  '/admin/_shell/nested/reports': typeof AdminShellNestedReportsRouteRouteWithChildren
  '/admin/_shell/nested/overview': typeof AdminShellNestedOverviewRoute
  '/admin/_shell/users/$userId': typeof AdminShellUsersUserIdRoute
  '/admin/_shell/users/new': typeof AdminShellUsersNewRoute
  '/admin/_shell/nested/': typeof AdminShellNestedIndexRoute
  '/admin/_shell/users/': typeof AdminShellUsersIndexRoute
  '/admin/_shell/nested/reports/regions': typeof AdminShellNestedReportsRegionsRouteRouteWithChildren
  '/admin/_shell/nested/reports/daily': typeof AdminShellNestedReportsDailyRoute
  '/admin/_shell/users/$userId_/edit': typeof AdminShellUsersUserIdEditRoute
  '/admin/_shell/nested/reports/': typeof AdminShellNestedReportsIndexRoute
  '/admin/_shell/nested/reports/regions/': typeof AdminShellNestedReportsRegionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/frontend'
    | '/403'
    | '/404'
    | '/admin/login'
    | '/frontend/login'
    | '/admin/'
    | '/frontend/'
    | '/admin/nested'
    | '/admin/users'
    | '/admin/403'
    | '/admin/404'
    | '/admin/auth-log'
    | '/admin/home'
    | '/admin/profile'
    | '/admin/tenants'
    | '/admin/widgets'
    | '/frontend/about'
    | '/frontend/home'
    | '/frontend/team'
    | '/admin/nested/reports'
    | '/admin/nested/overview'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/nested/'
    | '/admin/users/'
    | '/admin/nested/reports/regions'
    | '/admin/nested/reports/daily'
    | '/admin/users/$userId/edit'
    | '/admin/nested/reports/'
    | '/admin/nested/reports/regions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/404'
    | '/admin'
    | '/admin/login'
    | '/frontend'
    | '/frontend/login'
    | '/admin/403'
    | '/admin/404'
    | '/admin/auth-log'
    | '/admin/home'
    | '/admin/profile'
    | '/admin/tenants'
    | '/admin/widgets'
    | '/frontend/about'
    | '/frontend/home'
    | '/frontend/team'
    | '/admin/nested/overview'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/nested'
    | '/admin/users'
    | '/admin/nested/reports/daily'
    | '/admin/users/$userId/edit'
    | '/admin/nested/reports'
    | '/admin/nested/reports/regions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/frontend'
    | '/403'
    | '/404'
    | '/admin/_shell'
    | '/admin/login'
    | '/frontend/_shell'
    | '/frontend/login'
    | '/admin/'
    | '/frontend/'
    | '/admin/_shell/nested'
    | '/admin/_shell/users'
    | '/admin/_shell/403'
    | '/admin/_shell/404'
    | '/admin/_shell/auth-log'
    | '/admin/_shell/home'
    | '/admin/_shell/profile'
    | '/admin/_shell/tenants'
    | '/admin/_shell/widgets'
    | '/frontend/_shell/about'
    | '/frontend/_shell/home'
    | '/frontend/_shell/team'
    | '/admin/_shell/nested/reports'
    | '/admin/_shell/nested/overview'
    | '/admin/_shell/users/$userId'
    | '/admin/_shell/users/new'
    | '/admin/_shell/nested/'
    | '/admin/_shell/users/'
    | '/admin/_shell/nested/reports/regions'
    | '/admin/_shell/nested/reports/daily'
    | '/admin/_shell/users/$userId_/edit'
    | '/admin/_shell/nested/reports/'
    | '/admin/_shell/nested/reports/regions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  FrontendRouteRoute: typeof FrontendRouteRouteWithChildren
  R403Route: typeof R403Route
  R404Route: typeof R404Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frontend': {
      id: '/frontend'
      path: '/frontend'
      fullPath: '/frontend'
      preLoaderRoute: typeof FrontendRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frontend/': {
      id: '/frontend/'
      path: '/'
      fullPath: '/frontend/'
      preLoaderRoute: typeof FrontendIndexRouteImport
      parentRoute: typeof FrontendRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/frontend/login': {
      id: '/frontend/login'
      path: '/login'
      fullPath: '/frontend/login'
      preLoaderRoute: typeof FrontendLoginRouteImport
      parentRoute: typeof FrontendRouteRoute
    }
    '/frontend/_shell': {
      id: '/frontend/_shell'
      path: ''
      fullPath: '/frontend'
      preLoaderRoute: typeof FrontendShellRouteImport
      parentRoute: typeof FrontendRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/_shell': {
      id: '/admin/_shell'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/frontend/_shell/team': {
      id: '/frontend/_shell/team'
      path: '/team'
      fullPath: '/frontend/team'
      preLoaderRoute: typeof FrontendShellTeamRouteImport
      parentRoute: typeof FrontendShellRoute
    }
    '/frontend/_shell/home': {
      id: '/frontend/_shell/home'
      path: '/home'
      fullPath: '/frontend/home'
      preLoaderRoute: typeof FrontendShellHomeRouteImport
      parentRoute: typeof FrontendShellRoute
    }
    '/frontend/_shell/about': {
      id: '/frontend/_shell/about'
      path: '/about'
      fullPath: '/frontend/about'
      preLoaderRoute: typeof FrontendShellAboutRouteImport
      parentRoute: typeof FrontendShellRoute
    }
    '/admin/_shell/widgets': {
      id: '/admin/_shell/widgets'
      path: '/widgets'
      fullPath: '/admin/widgets'
      preLoaderRoute: typeof AdminShellWidgetsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/tenants': {
      id: '/admin/_shell/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminShellTenantsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/profile': {
      id: '/admin/_shell/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminShellProfileRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/home': {
      id: '/admin/_shell/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminShellHomeRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/auth-log': {
      id: '/admin/_shell/auth-log'
      path: '/auth-log'
      fullPath: '/admin/auth-log'
      preLoaderRoute: typeof AdminShellAuthLogRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/404': {
      id: '/admin/_shell/404'
      path: '/404'
      fullPath: '/admin/404'
      preLoaderRoute: typeof AdminShell404RouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/403': {
      id: '/admin/_shell/403'
      path: '/403'
      fullPath: '/admin/403'
      preLoaderRoute: typeof AdminShell403RouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/users': {
      id: '/admin/_shell/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminShellUsersRouteRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/nested': {
      id: '/admin/_shell/nested'
      path: '/nested'
      fullPath: '/admin/nested'
      preLoaderRoute: typeof AdminShellNestedRouteRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/users/': {
      id: '/admin/_shell/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminShellUsersIndexRouteImport
      parentRoute: typeof AdminShellUsersRouteRoute
    }
    '/admin/_shell/nested/': {
      id: '/admin/_shell/nested/'
      path: '/'
      fullPath: '/admin/nested/'
      preLoaderRoute: typeof AdminShellNestedIndexRouteImport
      parentRoute: typeof AdminShellNestedRouteRoute
    }
    '/admin/_shell/users/new': {
      id: '/admin/_shell/users/new'
      path: '/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminShellUsersNewRouteImport
      parentRoute: typeof AdminShellUsersRouteRoute
    }
    '/admin/_shell/users/$userId': {
      id: '/admin/_shell/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminShellUsersUserIdRouteImport
      parentRoute: typeof AdminShellUsersRouteRoute
    }
    '/admin/_shell/nested/overview': {
      id: '/admin/_shell/nested/overview'
      path: '/overview'
      fullPath: '/admin/nested/overview'
      preLoaderRoute: typeof AdminShellNestedOverviewRouteImport
      parentRoute: typeof AdminShellNestedRouteRoute
    }
    '/admin/_shell/nested/reports': {
      id: '/admin/_shell/nested/reports'
      path: '/reports'
      fullPath: '/admin/nested/reports'
      preLoaderRoute: typeof AdminShellNestedReportsRouteRouteImport
      parentRoute: typeof AdminShellNestedRouteRoute
    }
    '/admin/_shell/nested/reports/': {
      id: '/admin/_shell/nested/reports/'
      path: '/'
      fullPath: '/admin/nested/reports/'
      preLoaderRoute: typeof AdminShellNestedReportsIndexRouteImport
      parentRoute: typeof AdminShellNestedReportsRouteRoute
    }
    '/admin/_shell/users/$userId_/edit': {
      id: '/admin/_shell/users/$userId_/edit'
      path: '/$userId/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof AdminShellUsersUserIdEditRouteImport
      parentRoute: typeof AdminShellUsersRouteRoute
    }
    '/admin/_shell/nested/reports/daily': {
      id: '/admin/_shell/nested/reports/daily'
      path: '/daily'
      fullPath: '/admin/nested/reports/daily'
      preLoaderRoute: typeof AdminShellNestedReportsDailyRouteImport
      parentRoute: typeof AdminShellNestedReportsRouteRoute
    }
    '/admin/_shell/nested/reports/regions': {
      id: '/admin/_shell/nested/reports/regions'
      path: '/regions'
      fullPath: '/admin/nested/reports/regions'
      preLoaderRoute: typeof AdminShellNestedReportsRegionsRouteRouteImport
      parentRoute: typeof AdminShellNestedReportsRouteRoute
    }
    '/admin/_shell/nested/reports/regions/': {
      id: '/admin/_shell/nested/reports/regions/'
      path: '/'
      fullPath: '/admin/nested/reports/regions/'
      preLoaderRoute: typeof AdminShellNestedReportsRegionsIndexRouteImport
      parentRoute: typeof AdminShellNestedReportsRegionsRouteRoute
    }
  }
}

interface AdminShellNestedReportsRegionsRouteRouteChildren {
  AdminShellNestedReportsRegionsIndexRoute: typeof AdminShellNestedReportsRegionsIndexRoute
}

const AdminShellNestedReportsRegionsRouteRouteChildren: AdminShellNestedReportsRegionsRouteRouteChildren =
  {
    AdminShellNestedReportsRegionsIndexRoute:
      AdminShellNestedReportsRegionsIndexRoute,
  }

const AdminShellNestedReportsRegionsRouteRouteWithChildren =
  AdminShellNestedReportsRegionsRouteRoute._addFileChildren(
    AdminShellNestedReportsRegionsRouteRouteChildren,
  )

interface AdminShellNestedReportsRouteRouteChildren {
  AdminShellNestedReportsRegionsRouteRoute: typeof AdminShellNestedReportsRegionsRouteRouteWithChildren
  AdminShellNestedReportsDailyRoute: typeof AdminShellNestedReportsDailyRoute
  AdminShellNestedReportsIndexRoute: typeof AdminShellNestedReportsIndexRoute
}

const AdminShellNestedReportsRouteRouteChildren: AdminShellNestedReportsRouteRouteChildren =
  {
    AdminShellNestedReportsRegionsRouteRoute:
      AdminShellNestedReportsRegionsRouteRouteWithChildren,
    AdminShellNestedReportsDailyRoute: AdminShellNestedReportsDailyRoute,
    AdminShellNestedReportsIndexRoute: AdminShellNestedReportsIndexRoute,
  }

const AdminShellNestedReportsRouteRouteWithChildren =
  AdminShellNestedReportsRouteRoute._addFileChildren(
    AdminShellNestedReportsRouteRouteChildren,
  )

interface AdminShellNestedRouteRouteChildren {
  AdminShellNestedReportsRouteRoute: typeof AdminShellNestedReportsRouteRouteWithChildren
  AdminShellNestedOverviewRoute: typeof AdminShellNestedOverviewRoute
  AdminShellNestedIndexRoute: typeof AdminShellNestedIndexRoute
}

const AdminShellNestedRouteRouteChildren: AdminShellNestedRouteRouteChildren = {
  AdminShellNestedReportsRouteRoute:
    AdminShellNestedReportsRouteRouteWithChildren,
  AdminShellNestedOverviewRoute: AdminShellNestedOverviewRoute,
  AdminShellNestedIndexRoute: AdminShellNestedIndexRoute,
}

const AdminShellNestedRouteRouteWithChildren =
  AdminShellNestedRouteRoute._addFileChildren(
    AdminShellNestedRouteRouteChildren,
  )

interface AdminShellUsersRouteRouteChildren {
  AdminShellUsersUserIdRoute: typeof AdminShellUsersUserIdRoute
  AdminShellUsersNewRoute: typeof AdminShellUsersNewRoute
  AdminShellUsersIndexRoute: typeof AdminShellUsersIndexRoute
  AdminShellUsersUserIdEditRoute: typeof AdminShellUsersUserIdEditRoute
}

const AdminShellUsersRouteRouteChildren: AdminShellUsersRouteRouteChildren = {
  AdminShellUsersUserIdRoute: AdminShellUsersUserIdRoute,
  AdminShellUsersNewRoute: AdminShellUsersNewRoute,
  AdminShellUsersIndexRoute: AdminShellUsersIndexRoute,
  AdminShellUsersUserIdEditRoute: AdminShellUsersUserIdEditRoute,
}

const AdminShellUsersRouteRouteWithChildren =
  AdminShellUsersRouteRoute._addFileChildren(AdminShellUsersRouteRouteChildren)

interface AdminShellRouteChildren {
  AdminShellNestedRouteRoute: typeof AdminShellNestedRouteRouteWithChildren
  AdminShellUsersRouteRoute: typeof AdminShellUsersRouteRouteWithChildren
  AdminShell403Route: typeof AdminShell403Route
  AdminShell404Route: typeof AdminShell404Route
  AdminShellAuthLogRoute: typeof AdminShellAuthLogRoute
  AdminShellHomeRoute: typeof AdminShellHomeRoute
  AdminShellProfileRoute: typeof AdminShellProfileRoute
  AdminShellTenantsRoute: typeof AdminShellTenantsRoute
  AdminShellWidgetsRoute: typeof AdminShellWidgetsRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellNestedRouteRoute: AdminShellNestedRouteRouteWithChildren,
  AdminShellUsersRouteRoute: AdminShellUsersRouteRouteWithChildren,
  AdminShell403Route: AdminShell403Route,
  AdminShell404Route: AdminShell404Route,
  AdminShellAuthLogRoute: AdminShellAuthLogRoute,
  AdminShellHomeRoute: AdminShellHomeRoute,
  AdminShellProfileRoute: AdminShellProfileRoute,
  AdminShellTenantsRoute: AdminShellTenantsRoute,
  AdminShellWidgetsRoute: AdminShellWidgetsRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminShellRoute: AdminShellRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface FrontendShellRouteChildren {
  FrontendShellAboutRoute: typeof FrontendShellAboutRoute
  FrontendShellHomeRoute: typeof FrontendShellHomeRoute
  FrontendShellTeamRoute: typeof FrontendShellTeamRoute
}

const FrontendShellRouteChildren: FrontendShellRouteChildren = {
  FrontendShellAboutRoute: FrontendShellAboutRoute,
  FrontendShellHomeRoute: FrontendShellHomeRoute,
  FrontendShellTeamRoute: FrontendShellTeamRoute,
}

const FrontendShellRouteWithChildren = FrontendShellRoute._addFileChildren(
  FrontendShellRouteChildren,
)

interface FrontendRouteRouteChildren {
  FrontendShellRoute: typeof FrontendShellRouteWithChildren
  FrontendLoginRoute: typeof FrontendLoginRoute
  FrontendIndexRoute: typeof FrontendIndexRoute
}

const FrontendRouteRouteChildren: FrontendRouteRouteChildren = {
  FrontendShellRoute: FrontendShellRouteWithChildren,
  FrontendLoginRoute: FrontendLoginRoute,
  FrontendIndexRoute: FrontendIndexRoute,
}

const FrontendRouteRouteWithChildren = FrontendRouteRoute._addFileChildren(
  FrontendRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  FrontendRouteRoute: FrontendRouteRouteWithChildren,
  R403Route: R403Route,
  R404Route: R404Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
